//go:build !ignore_autogenerated

// Code generated by handmade controller-gen substitute. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CadenceSpec) DeepCopyInto(out *CadenceSpec) {
	*out = *in
	if in.JitterPercentage != nil {
		in, out := &in.JitterPercentage, &out.JitterPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CadenceSpec.
func (in *CadenceSpec) DeepCopy() *CadenceSpec {
	if in == nil {
		return nil
	}
	out := new(CadenceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *LabelSelector) DeepCopyInto(out *LabelSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LabelSelector) DeepCopy() *LabelSelector {
	if in == nil {
		return nil
	}
	out := new(LabelSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *LabelSelectorRequirement) DeepCopyInto(out *LabelSelectorRequirement) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *LabelSelectorRequirement) DeepCopy() *LabelSelectorRequirement {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorRequirement)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(ClusterReference)
		**out = **in
	}
}

func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

func (in *TelemetrySource) DeepCopyInto(out *TelemetrySource) {
	*out = *in
	if in.IntervalSeconds != nil {
		in, out := &in.IntervalSeconds, &out.IntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TelemetrySource) DeepCopy() *TelemetrySource {
	if in == nil {
		return nil
	}
	out := new(TelemetrySource)
	in.DeepCopyInto(out)
	return out
}

func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]TelemetrySource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DriftPolicy) DeepCopyInto(out *DriftPolicy) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]DriftCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemediationHints != nil {
		in, out := &in.RemediationHints, &out.RemediationHints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DriftPolicy) DeepCopy() *DriftPolicy {
	if in == nil {
		return nil
	}
	out := new(DriftPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *DriftResourceRef) DeepCopyInto(out *DriftResourceRef) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *DriftResourceRef) DeepCopy() *DriftResourceRef {
	if in == nil {
		return nil
	}
	out := new(DriftResourceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *DriftCheck) DeepCopyInto(out *DriftCheck) {
	*out = *in
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(float64)
		**out = **in
	}
}

func (in *DriftCheck) DeepCopy() *DriftCheck {
	if in == nil {
		return nil
	}
	out := new(DriftCheck)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RolloutPolicy != nil {
		in, out := &in.RolloutPolicy, &out.RolloutPolicy
		*out = new(RolloutPolicy)
		(*in).DeepCopyInto(*out)
	}
}

func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GitOpsSpec) DeepCopyInto(out *GitOpsSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

func (in *GitOpsSpec) DeepCopy() *GitOpsSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutPolicy) DeepCopyInto(out *RolloutPolicy) {
	*out = *in
	if in.MaxParallelRemediations != nil {
		in, out := &in.MaxParallelRemediations, &out.MaxParallelRemediations
		*out = new(int32)
		**out = **in
	}
	if in.PauseSeconds != nil {
		in, out := &in.PauseSeconds, &out.PauseSeconds
		*out = new(int32)
		**out = **in
	}
	if in.VerificationGates != nil {
		in, out := &in.VerificationGates, &out.VerificationGates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *RolloutPolicy) DeepCopy() *RolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(RolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *VerificationProbe) DeepCopyInto(out *VerificationProbe) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		*out = new(int32)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *VerificationProbe) DeepCopy() *VerificationProbe {
	if in == nil {
		return nil
	}
	out := new(VerificationProbe)
	in.DeepCopyInto(out)
	return out
}

func (in *VerificationSpec) DeepCopyInto(out *VerificationSpec) {
	*out = *in
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = make([]VerificationProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VerificationSpec) DeepCopy() *VerificationSpec {
	if in == nil {
		return nil
	}
	out := new(VerificationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AIPlannerSpec) DeepCopyInto(out *AIPlannerSpec) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

func (in *AIPlannerSpec) DeepCopy() *AIPlannerSpec {
	if in == nil {
		return nil
	}
	out := new(AIPlannerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KineticOpsLoopSpec) DeepCopyInto(out *KineticOpsLoopSpec) {
	*out = *in
	in.Cadence.DeepCopyInto(&out.Cadence)
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DriftPolicies != nil {
		in, out := &in.DriftPolicies, &out.DriftPolicies
		*out = make([]DriftPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Remediation.DeepCopyInto(&out.Remediation)
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(VerificationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AIPlanner != nil {
		in, out := &in.AIPlanner, &out.AIPlanner
		*out = new(AIPlannerSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *KineticOpsLoopSpec) DeepCopy() *KineticOpsLoopSpec {
	if in == nil {
		return nil
	}
	out := new(KineticOpsLoopSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
}

func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

func (in *LastRemediationStatus) DeepCopyInto(out *LastRemediationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

func (in *LastRemediationStatus) DeepCopy() *LastRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(LastRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KineticOpsLoopStatus) DeepCopyInto(out *KineticOpsLoopStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.LastRemediation != nil {
		in, out := &in.LastRemediation, &out.LastRemediation
		*out = new(LastRemediationStatus)
		(*in).DeepCopyInto(*out)
	}
}

func (in *KineticOpsLoopStatus) DeepCopy() *KineticOpsLoopStatus {
	if in == nil {
		return nil
	}
	out := new(KineticOpsLoopStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KineticOpsLoop) DeepCopyInto(out *KineticOpsLoop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KineticOpsLoop) DeepCopy() *KineticOpsLoop {
	if in == nil {
		return nil
	}
	out := new(KineticOpsLoop)
	in.DeepCopyInto(out)
	return out
}

func (in *KineticOpsLoop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KineticOpsLoopList) DeepCopyInto(out *KineticOpsLoopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KineticOpsLoop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KineticOpsLoopList) DeepCopy() *KineticOpsLoopList {
	if in == nil {
		return nil
	}
	out := new(KineticOpsLoopList)
	in.DeepCopyInto(out)
	return out
}

func (in *KineticOpsLoopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
