apiVersion: v1
kind: Secret
metadata:
  name: drewbai-gitops-creds
  namespace: kineticops-system
  labels:
    app.kubernetes.io/name: kineticops
    app.kubernetes.io/part-of: kineticops
type: Opaque
stringData:
  username: drewbai
  token: PLACEHOLDER_PERSONAL_ACCESS_TOKEN
  known_hosts: |
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMf4Uz+w9NjZ1J9sw6baMEwx4RbJ/Q0H5GJwVw5y8c+
